"""kubectl repository rules"""

# buildifier: disable=bzl-visibility
load("//helm/private:repositories.bzl", "host_platform")

_KUBECTL_TOOLCHAIN_BUILD_CONTENT = """\
load("@rules_helm//k8s:kubectl_toolchain.bzl", "kubectl_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "kubectl_bin",
    srcs = ["{bin}"],
)

kubectl_toolchain(
    name = "kubectl_toolchain",
    kubectl = ":kubectl_bin",
)

alias(
    name = "{name}",
    actual = ":kubectl_toolchain",
)
"""

_WORKSPACE_CONTENT = """\
workspace(name = "{}")
"""

def _kubectl_toolchain_repository_impl(repository_ctx):
    if repository_ctx.attr.platform.startswith("windows"):
        bin = "kubectl.exe"
    else:
        bin = "kubectl"

    # kubectl is published as a bare binary rather than an archive.
    repository_ctx.download(
        repository_ctx.attr.urls,
        output = bin,
        sha256 = repository_ctx.attr.sha256,
        executable = True,
    )

    repository_ctx.file("BUILD.bazel", _KUBECTL_TOOLCHAIN_BUILD_CONTENT.format(
        name = repository_ctx.original_name,
        bin = bin,
    ))

    repository_ctx.file("WORKSPACE.bazel", _WORKSPACE_CONTENT.format(
        repository_ctx.name,
    ))

    # Bazel <8.3.0 lacks repository_ctx.repo_metadata
    if not hasattr(repository_ctx, "repo_metadata"):
        return None

    return repository_ctx.repo_metadata(reproducible = True)

kubectl_toolchain_repository = repository_rule(
    implementation = _kubectl_toolchain_repository_impl,
    doc = "A repository rule for downloading a kubectl binary and generating a kubectl toolchain definition.",
    attrs = {
        "platform": attr.string(
            doc = "Platform the kubectl executable was built for (e.g. `linux-amd64`).",
            mandatory = True,
        ),
        "sha256": attr.string(
            doc = "The expected hex-encoded SHA-256 of the downloaded binary, as published in the upstream `.sha256` files.",
            mandatory = True,
        ),
        "urls": attr.string_list(
            doc = """\
A list of URLs to the kubectl binary.

URLs are tried in order until one succeeds, so you should list local mirrors first.
If all downloads fail, the rule will fail.
""",
            mandatory = True,
        ),
    },
)

def _kubectl_host_alias_repository_impl(repository_ctx):
    is_windows = repository_ctx.os.name.lower().find("windows") != -1
    ext = ".exe" if is_windows else ""

    repository_ctx.file("BUILD.bazel", """# @generated by @rules_helm//k8s/private/kubectl_repositories.bzl
load("@bazel_lib//lib:copy_file.bzl", "copy_file")

package(default_visibility = ["//visibility:public"])

copy_file(
    name = "kubectl",
    src = "@{prefix}_{platform}_bin//:kubectl_bin",
    out = "kubectl-{version}{ext}",
    is_executable = True,
    allow_symlink = True,
)
""".format(
        prefix = repository_ctx.attr.toolchain_repo_prefix,
        platform = host_platform(repository_ctx),
        ext = ext,
        version = repository_ctx.attr.version,
    ))

kubectl_host_alias_repository = repository_rule(
    implementation = _kubectl_host_alias_repository_impl,
    doc = """Creates a repository with a shorter name meant for the host platform, which contains
    a BUILD.bazel file that exports the host platform's kubectl binary.
    """,
    attrs = {
        "toolchain_repo_prefix": attr.string(
            doc = "The name prefix for binary repos to alias. The host alias constructs the full repo name as {prefix}_{platform}_bin.",
            mandatory = True,
        ),
        "version": attr.string(
            doc = "The version of kubectl the alias points at. Used to name the output binary.",
            mandatory = True,
        ),
    },
)
