"""Utilities for container images"""

load("//helm/private:json_extractor.bzl", "json_extractor")

ImageRepositoryInfo = provider(
    doc = "Repository and image information for a given rules_oci or rules_img image target",
    fields = {
        "manifest_file": "File (optional): The manifest JSON file for rules_img images",
        "oci_layout": "File (optional): The OCI layout directory for rules_oci images (contains index.json)",
        "remote_tags_file": "File (optional): The file containing remote tags (one per line) used for the target",
        "repository_file": "File: The file containing the repository path for the target",
    },
)

def _image_repository_aspect_img_pull(target, ctx):
    """Collect repository info from an `image_import` target generated by `img_pull`."""

    # `image_import` exposes the pulled root manifest (or index) blob as its
    # only default output. Prefer it over re-writing the inline `data` attribute
    # so the digest is computed from the exact bytes that were pulled.
    manifest_file = None
    files = target[DefaultInfo].files.to_list()
    if len(files) == 1:
        manifest_file = files[0]
    else:
        digest = getattr(ctx.rule.attr, "digest", None)
        data = getattr(ctx.rule.attr, "data", None) or {}
        if not digest or digest not in data:
            fail("image_import target {} does not provide a root manifest".format(target.label))

        manifest_file = ctx.actions.declare_file("{}.rules_helm.manifest.json".format(target.label.name))
        ctx.actions.write(
            output = manifest_file,
            content = data[digest],
        )

    # `img_pull` records every registry it may pull from in `registries`, in the
    # order they are tried: the primary `registry` first, followed by any
    # mirrors. Use the first entry so the chart references the primary
    # registry. Older versions of rules_img expose a single `registry` instead.
    registry = None
    registries = getattr(ctx.rule.attr, "registries", None)
    if registries:
        registry = registries[0]
    elif getattr(ctx.rule.attr, "registry", None):
        registry = ctx.rule.attr.registry

    if not registry:
        fail("image_import target {} must have either a `registry` or `registries` attribute".format(target.label))

    repository = getattr(ctx.rule.attr, "repository", None)
    if not repository:
        fail("image_import target {} must have a `repository` attribute".format(target.label))

    # Remove protocol from registry if present
    registry_clean = registry.replace("https://", "").replace("http://", "")

    repository_file = ctx.actions.declare_file("{}.rules_helm.repository.txt".format(target.label.name))
    ctx.actions.write(
        output = repository_file,
        content = "{}/{}".format(registry_clean, repository),
    )

    remote_tags_file = None
    tag = getattr(ctx.rule.attr, "tag", None)
    if tag:
        remote_tags_file = ctx.actions.declare_file("{}.rules_helm.tags.txt".format(target.label.name))
        ctx.actions.write(
            output = remote_tags_file,
            content = tag,
        )

    return [ImageRepositoryInfo(
        repository_file = repository_file,
        manifest_file = manifest_file,
        oci_layout = None,
        remote_tags_file = remote_tags_file,
    )]

def _image_repository_aspect_img_push(target, ctx):
    repository_file = None
    remote_tags_file = None
    manifest_file = None

    if not hasattr(ctx.rule.attr, "image") or not ctx.rule.attr.image:
        fail("image_push target {} must have an `image` attribute".format(target.label))

    # Get the image file from the image attribute
    if hasattr(ctx.rule.files, "image") and ctx.rule.files.image:
        manifest_file = ctx.rule.files.image[0]
    elif hasattr(ctx.rule.file, "image") and ctx.rule.file.image:
        manifest_file = ctx.rule.file.image
    else:
        fail("image_push target {} `image` attribute must provide files".format(target.label))

    # First we try and use the push metadata file generated by the rule, which
    # is preferred because it contains expanded templates
    metadata_file = None

    info = target[DefaultInfo]
    files = []

    # Versions < 0.3.0 have the metadata in files
    if hasattr(info, "files") and info.files:
        files = files + info.files.to_list()

    # Versions >= 0.3.0 have it in the runfiles
    if hasattr(info, "default_runfiles") and info.default_runfiles:
        runfiles = info.default_runfiles
        if hasattr(runfiles, "files") and runfiles.files:
            files += files + runfiles.files.to_list()

    for file in files:
        if file.basename == "{}.json".format(ctx.label.name):
            metadata_file = file
            break

    if metadata_file:
        repository_template = """
        {{- with index .operations 0 -}}
            {{- $registry := .registry -}}
            {{- $registry = trimPrefix $registry "https://" -}}
            {{- $registry = trimPrefix $registry "http://" -}}

            {{- $registry }}/{{ .repository -}}
        {{- end -}}
        """

        repository_file = ctx.actions.declare_file("{}.rules_helm.repository.txt".format(target.label.name))
        json_extractor(ctx, metadata_file, repository_file, repository_template)

        tags_template = """
        {{- with index .operations 0 -}}
            {{- range $tag := .tags -}}
                {{- $tag | println -}}
            {{- end -}}
        {{- end -}}
        """

        remote_tags_file = ctx.actions.declare_file("{}.rules_helm.tags.txt".format(target.label.name))
        json_extractor(ctx, metadata_file, remote_tags_file, tags_template)

    # Next alternative, try and use attrs from the rule itself
    if repository_file == None:
        if not hasattr(ctx.rule.attr, "registry") or not ctx.rule.attr.registy:
            fail("image_push target {} must have a `registry` attribute".format(target.label))

        registry = ctx.rule.attr.registry

        if not hasattr(ctx.rule.attr, "repository") or not ctx.rule.attr.repository:
            fail("image_push target {} must have a `repository` attribute".format(target.label))

        repository = ctx.rule.attr.repository

        # Remove protocol from registry if present
        registry_clean = registry.replace("https://", "").replace("http://", "")
        full_repo = "{}/{}".format(registry_clean, repository)

        repository_file = ctx.actions.declare_file("{}.rules_helm.repository.txt".format(target.label.name))
        ctx.actions.write(
            output = repository_file,
            content = full_repo,
        )

    if remote_tags_file == None:
        tag_list = None

        if hasattr(ctx.rule.attr, "tag") and ctx.rule.attr.tag:
            tag_list = [ctx.rule.attr.tag]
        elif hasattr(ctx.rule.attr, "tag_list") and ctx.rule.attr.tag_list:
            tag_list = ctx.rule.attr.tag_list

        # If either tag or tag_list was set, we produce a tag list file
        # ourselves
        if tag_list != None:
            remote_tags_file = ctx.actions.declare_file("{}.rules_helm.tags.txt".format(target.label.name))
            ctx.actions.write(
                output = remote_tags_file,
                content = "\n".join(tag_list),
            )
        elif hasattr(ctx.rule.file, "tag_file") and ctx.rule.file.tag_file:
            # Tags can also be provided as a file, in which case we can re-use
            # it
            remote_tags_file = ctx.rule.file.tag_file

    return [ImageRepositoryInfo(
        repository_file = repository_file,
        manifest_file = manifest_file,
        oci_layout = None,
        remote_tags_file = remote_tags_file,
    )]

def _image_repository_aspect_oci_push(target, ctx):
    repository_file = None
    remote_tags_file = None

    # The repository can either be provided as a string attr, or as a file
    if hasattr(ctx.rule.attr, "repository") and ctx.rule.attr.repository:
        repository_file = ctx.actions.declare_file("{}.rules_helm.repository.txt".format(target.label.name))
        ctx.actions.write(
            output = repository_file,
            content = ctx.rule.attr.repository,
        )
    elif hasattr(ctx.rule.file, "repository_file") and ctx.rule.file.repository_file:
        repository_file = ctx.rule.file.repository_file

    if repository_file == None:
        fail("oci_push target {} must have either a `repository` or `repository_file` attribute".format(target.label.name))

    if hasattr(ctx.rule.file, "remote_tags") and ctx.rule.file.remote_tags:
        remote_tags_file = ctx.rule.file.remote_tags

    if not hasattr(ctx.rule.file, "image"):
        fail("oci_push target {} must have an `image` attribute".format(target.label))

    return [ImageRepositoryInfo(
        repository_file = repository_file,
        oci_layout = ctx.rule.file.image,
        manifest_file = None,
        remote_tags_file = remote_tags_file,
    )]

def _image_repository_aspect_impl(target, ctx):
    if ctx.rule.kind == "image_import":
        return _image_repository_aspect_img_pull(target, ctx)

    if ctx.rule.kind == "image_push" or hasattr(ctx.rule.attr, "registry"):
        return _image_repository_aspect_img_push(target, ctx)

    return _image_repository_aspect_oci_push(target, ctx)

# This aspect exists because rules_oci and rules_img don't provide a provider
# that cleanly publishes this information but for the helm rules, it's
# absolutely necessary that an image's repository and digest are knowable.
# If rules_oci/rules_img decide to define their own provider for this (which they should)
# then this should be deleted in favor of that.
image_repository_aspect = aspect(
    doc = "Provides the repository and image_root for a given oci_push, image_push or image_import target",
    implementation = _image_repository_aspect_impl,
    attrs = {
        "_json_extractor": attr.label(
            doc = "Tool for extracting data from json files",
            cfg = "exec",
            executable = True,
            default = Label("//helm/private/json_extractor"),
        ),
    },
)
